apiVersion: v1
kind: Pod
metadata:
  name: gpu-example-pod
spec:
  restartPolicy: Never
  containers:
    - name: gpu-container
      image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/ci-image:pytorch-linux-jammy-cuda12.8-cudnn9-py3-gcc9-inductor-benchmarks-ffeded2190e403ba38d2387ad7d31aeee6498475
      resources:
        requests:
          cpu: "10"
          memory: "30Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "10"
          memory: "30Gi"
          nvidia.com/gpu: "1"
      command:
        - /bin/bash
        - /opt/script/run.sh
      volumeMounts:
        - name: script-volume
          mountPath: /opt/script
        - name: scratch-volume
          mountPath: /scratch
    - name: gpu-container-2
      image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/ci-image:pytorch-linux-jammy-cuda12.8-cudnn9-py3-gcc9-inductor-benchmarks-ffeded2190e403ba38d2387ad7d31aeee6498475
      resources:
        requests:
          cpu: "10"
          memory: "30Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "10"
          memory: "30Gi"
          nvidia.com/gpu: "1"
      command:
        - /bin/bash
        - /opt/script/run.sh
      volumeMounts:
        - name: script-volume
          mountPath: /opt/script
        - name: scratch-volume-2
          mountPath: /scratch
  volumes:
    - name: script-volume
      configMap:
        name: gpu-script
        defaultMode: 0755
    - name: scratch-volume
      emptyDir:
        sizeLimit: "800Gi"
    - name: scratch-volume-2
      emptyDir:
        sizeLimit: "800Gi"
  tolerations:
    - key: "jeanTest"
      operator: "Equal"
      value: "testit"
      effect: "NoSchedule"
  # tolerations:
  #   - key: "nvidia.com/gpu"
  #     operator: "Exists"
  #     effect: "NoSchedule"
  #   - key: "node.kubernetes.io/not-ready"
  #     operator: "Exists"
  #     effect: "NoExecute"
  #     tolerationSeconds: 300
  #   - key: "node.kubernetes.io/unreachable"
  #     operator: "Exists"
  #     effect: "NoExecute"
  #     tolerationSeconds: 300
  # priority: 0
  # enableServiceLinks: true
  # preemptionPolicy: PreemptLowerPriority
  # nodeSelector:
  #   GpuType: a100
  #   topology.kubernetes.io/zone: us-east-2a
  nodeName: ip-10-0-12-170.us-east-2.compute.internal
